### PR TITLE
Added optional theme props type support.

### PR DESCRIPTION
**Pull request by je2ryw**

### CODE REVIEW

**Comment by duro** [comment]
@jacob-ebey Any chance of getting this reviewed and merged?

**Comment by jacob-ebey** [comment]
Let me get CI setup here in the next few days and I'll get on this for ya.

**Comment by jacob-ebey** [comment]
I'm going to actually remove the examples folder and get some tests setup. I'm going to close this PR.

Thanks for the contribution!

**Comment by je2ryw** [comment]
@jacob-ebey the latest 0.0.10 published npm package does not have the /lib directory, only /src directory with typescript source code file.

**Comment by jacob-ebey** [comment]
@duro, yes this was Incorporated into master. I was not happy with the way the project was setup as well as the code style.

@je2ryw, Thanks for the catch. Seems I forgot to persist the workspace after build on the CI server.

Once 0.0.11 finishes building we should be good to go.

**Pull request closed without merging**
